// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoAN7KgcCcA8w0P9xlO8XLeCVDNCkVNMQ',
    appId: '1:335118881570:web:06116c8e51afaf35eb4b7b',
    messagingSenderId: '335118881570',
    projectId: 'mijanodrive-peru',
    authDomain: 'mijanodrive-peru.firebaseapp.com',
    storageBucket: 'mijanodrive-peru.firebasestorage.app',
    measurementId: 'G-62YT52XBH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMhmdJobdeH1aUJ87XLw3yRnqm-ufWLGc',
    appId: '1:335118881570:android:0a7f51b587f65f05eb4b7b',
    messagingSenderId: '335118881570',
    projectId: 'mijanodrive-peru',
    storageBucket: 'mijanodrive-peru.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNSlNr8Ytx_-tMDqayts6YQ7b4hRFHkQ',
    appId: '1:335118881570:ios:81a661b4a92c7c4beb4b7b',
    messagingSenderId: '335118881570',
    projectId: 'mijanodrive-peru',
    storageBucket: 'mijanodrive-peru.firebasestorage.app',
    iosBundleId: 'net.minicodevelopers.mijanoDriveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlNSlNr8Ytx_-tMDqayts6YQ7b4hRFHkQ',
    appId: '1:335118881570:ios:81a661b4a92c7c4beb4b7b',
    messagingSenderId: '335118881570',
    projectId: 'mijanodrive-peru',
    storageBucket: 'mijanodrive-peru.firebasestorage.app',
    iosBundleId: 'net.minicodevelopers.mijanoDriveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoAN7KgcCcA8w0P9xlO8XLeCVDNCkVNMQ',
    appId: '1:335118881570:web:70eb3631f3bffe16eb4b7b',
    messagingSenderId: '335118881570',
    projectId: 'mijanodrive-peru',
    authDomain: 'mijanodrive-peru.firebaseapp.com',
    storageBucket: 'mijanodrive-peru.firebasestorage.app',
    measurementId: 'G-6FRR5WEYE7',
  );
}
